# Generated by Django 5.1.5 on 2025-02-05 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminUser', '0002_categorydistance_gmaildistance_imagedistance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('given_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Other', 'Other')], max_length=10)),
                ('born_date', models.DateField()),
                ('born_place', models.CharField(max_length=255)),
                ('born_country', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('mail_address', models.EmailField(max_length=255)),
                ('counselling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='adminUser.counselling')),
            ],
        ),
    ]
